on:
  push:
    branches: [ feature/*, develop ]
  pull_request:
    branches: [ main, release, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Validate data (Great Expectations)
        run: |
          pip install great_expectations
          
          # 2. Agrega el directorio de binarios del usuario al PATH para este mismo shell.
          # Esto es crucial para que el comando great_expectations se encuentre justo después de la instalación.
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          
          # 3. Ejecuta el checkpoint de Great Expectations.
          # Como la instalación y la actualización del PATH están en el mismo bloque 'run',
          # el shell debería tener el PATH correcto al momento de ejecutar este comando.
          great_expectations checkpoint run my_checkpoint
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8 black
          black --check .
          flake8 .

      - name: Run pytest
        run: |
          pytest --junitxml=reports/junit.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml dime como puedo probar