on:
  push:
    branches: [ feature/*, develop ]
  pull_request:
    branches: [ main, release, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      #- name: Validate data (Great Expectations)
      #  run: |
      #    pip install great_expectations==0.18.0
      #    great_expectations checkpoint run my_checkpoint
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8 black
          black .
          black --check .
          flake8 .

      - name: Run pytest
        run: |
          pytest --junitxml=reports/junit.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml dime como puedo probar